name: NodeJS-NPM Continuous Integration
on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        description: Branch/Tag/Commit SHA
        required: false
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ inputs.branch }}
  cancel-in-progress: true
jobs:
  build:
    uses: capgemini-ga-demo/github_centralized_workflows/.github/workflows/nodejs-npm-ci.yml@develop
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      node-version: '20.x'
      build-command: npm run build
      test-command: npm test
      publish-command: npm publish